services:
  auth-service:
    container_name: auth-service-container
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    env_file:
      - .env
    networks:
      - go-servise-base_local-network
    ports:
      - "${HTTP_PORT:-8002}:${HTTP_PORT:-8002}"
      - "${GRPC_PORT:-50051}:${GRPC_PORT:-50051}"
    labels:
      - 'traefik.enable=true'
      # Router rule
      - "traefik.http.routers.auth.rule=PathPrefix(`/api/v1/auth`)"
      - "traefik.http.routers.auth.entrypoints=web"
      # Port внутри контейнера
      - "traefik.http.services.auth.loadbalancer.server.port=8002"

networks:
  go-servise-base_local-network:
    external: true
