services:
  auth-service:
    container_name: auth-service-container
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    env_file:
      - .env
    networks:
      - go-servise-base_local-network
    ports:
      - "${HTTP_PORT:-8002}:${HTTP_PORT:-8002}"
    labels:
      - "a=localExample"
      - "traefik.enable=true"
      - "traefik.http.routers.auth.rule=PathPrefix(`/api/v1/auth`)"
      - "traefik.http.routers.auth.entrypoints=web"

networks:
  go-servise-base_local-network:
    external: true
